import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = localFont({
  src: [
    { path: "../public/fonts/Lato/Lato-Hairline.woff2", weight: "100", style: "normal" },
    { path: "../public/fonts/Lato/Lato-HairlineItalic.woff2", weight: "100", style: "italic" },

    { path: "../public/fonts/Lato/Lato-Light.woff2", weight: "300", style: "normal" },
    { path: "../public/fonts/Lato/Lato-LightItalic.woff2", weight: "300", style: "italic" },

    { path: "../public/fonts/Lato/Lato-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Lato/Lato-Italic.woff2", weight: "400", style: "italic" },

    { path: "../public/fonts/Lato/Lato-Bold.woff2", weight: "700", style: "normal" },
    { path: "../public/fonts/Lato/Lato-BoldItalic.woff2", weight: "700", style: "italic" },

    { path: "../public/fonts/Lato/Lato-Black.woff2", weight: "900", style: "normal" },
    { path: "../public/fonts/Lato/Lato-BlackItalic.woff2", weight: "900", style: "italic" },
  ],
  variable: "--font-lato",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        {children}
      </body>
    </html>
  );
}
